development:
  username: apitest
  password: apitest
  shoulder: 10.5072/bodleian
  url: https://mds.datacite.org/
  resolver_url: http://dx.doi.org/
test:
  username: apitest
  password: apitest
  shoulder: 10.5072/bodleian
  url: https://mds.datacite.org/
  resolver_url: http://dx.doi.org/
production:
  username: apitest
  password: apitest
  shoulder: 10.5072/bodleian
  url: https://mds.datacite.org/
  resolver_url: http://dx.doi.org/
